# Default monitoring settings
SLOW_THRESHOLD = 2.0
REQUEST_TIMEOUT = 10
AUTO_HEAL_ENABLED = False
TARGET_CONTAINER_NAME = "your-container-name"
CPU_THRESHOLD = 80
RAM_THRESHOLD = 85
DISK_THRESHOLD = 90
SSL_EXPIRY_THRESHOLD_DAYS = 15